apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: echo
  name: wik-dps-tp04
  labels:
    app: wik-dps-tp04
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: wik-dps-tp04
  template:
    metadata:
      labels:
        app: wik-dps-tp04
    spec:
      containers:
        - name: wik-dps-tp04
          image: registry.cluster.wik.cloud/public/echo:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
